apiVersion: apps/v1
kind: Deployment
metadata:
  name: testrestapi-deployment
  labels:
    app: testrestapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testrestapi
  template:
    metadata:
      labels:
        app: testrestapi
    spec:
      containers:
      - name: testrestapi
        image: testrestapi:latest
        ports:
        - containerPort: 8080
